const VEHICLES = [
  // ============ CIVILES (compra con cash del juego) ============
  { name: "Citrion Buddy", slug: "citrion-buddy", category: "civil", type: "Compacto", priceCash: 1000, gold: 90, topSpeed: 38, accel: "—", rarity: "Común" },
  { name: "Nissari Versia", slug: "nissari-versia", category: "civil", type: "Sedán", priceCash: 2000, gold: 150, topSpeed: 108, accel: "10.2s", rarity: "Común" },
  { name: "Tayora Royal Touring", slug: "tayora-royal-touring", category: "civil", type: "Sedán", priceCash: 7500, gold: 250, topSpeed: 140, accel: "7.5s", rarity: "Común" },
  { name: "Dager Durance R/T", slug: "dager-durance-rt", category: "civil", type: "Muscle", priceCash: 10000, gold: 300, topSpeed: 145, accel: "6.2s", rarity: "Común" },
  { name: "Mammoth Patriot", slug: "mammoth-patriot", category: "civil", type: "SUV", priceCash: 10000, gold: 300, topSpeed: 115, accel: "6.7s", rarity: "Común" },
  { name: "Chevran Silverline", slug: "chevran-silverline", category: "civil", type: "Sedán", priceCash: 10500, gold: 320, topSpeed: 132, accel: "6.8s", rarity: "Común" },
  { name: "Bracken Trailmaster 150", slug: "bracken-trailmaster-150", category: "civil", type: "Pickup", priceCash: 12500, gold: 350, topSpeed: 112, accel: "6.9s", rarity: "Común" },
  { name: "Hondo CR250X", slug: "hondo-cr250x", category: "civil", type: "Moto", priceCash: 15000, gold: 400, topSpeed: 80, accel: "3.2s", rarity: "Común" },
  { name: "Chevran Silverline HD", slug: "chevran-silverline-hd", category: "civil", type: "Sedán", priceCash: 16000, gold: 450, topSpeed: 120, accel: "9.0s", rarity: "Común" },
  { name: "Beamer M135X", slug: "beamer-m135x", category: "civil", type: "Deportivo", priceCash: 20000, gold: 550, topSpeed: 155, accel: "4.7s", rarity: "Común" },
  { name: "Beamer E30R", slug: "beamer-e30r", category: "civil", type: "Deportivo", priceCash: 30000, gold: 750, topSpeed: 146, accel: "6.6s", rarity: "Común" },
  { name: "Auvio R3S", slug: "auvio-r3s", category: "civil", type: "Deportivo", priceCash: 35000, gold: 850, topSpeed: 155, accel: "3.9s", rarity: "Común" },
  { name: "Dager Defiant", slug: "dager-defiant", category: "civil", type: "Muscle", priceCash: 70000, gold: 1500, topSpeed: 170, accel: "5.0s", rarity: "Raro" },
  { name: "Beamer G82R", slug: "beamer-g82r", category: "civil", type: "Deportivo", priceCash: 90000, gold: 1900, topSpeed: 180, accel: "4.1s", rarity: "Raro" },
  { name: "Buxton Grandmaster 57", slug: "buxton-grandmaster-57", category: "civil", type: "Sedán", priceCash: 100000, gold: 2100, topSpeed: 115, accel: "10.5s", rarity: "Raro" },
  { name: "Mercel G63 AMX", slug: "mercel-g63-amx", category: "civil", type: "SUV", priceCash: 100000, gold: 2100, topSpeed: 149, accel: "4.3s", rarity: "Raro" },
  { name: "Caddex Escalo", slug: "caddex-escalo", category: "civil", type: "SUV", priceCash: 120000, gold: 2500, topSpeed: 165, accel: "5.2s", rarity: "Raro" },
  { name: "Fjord Townline Stretch", slug: "fjord-townline-stretch", category: "civil", type: "Limusina", priceCash: 130000, gold: 2700, topSpeed: 120, accel: "6.1s", rarity: "Raro" },
  { name: "Rennex T9", slug: "rennex-t9", category: "civil", type: "Superdeportivo", priceCash: 150000, gold: 3100, topSpeed: 200, accel: "3.5s", rarity: "Épico" },
  { name: "Rennex Crestline", slug: "rennex-crestline", category: "civil", type: "Sedán", priceCash: 160000, gold: 3300, topSpeed: 158, accel: "5.4s", rarity: "Épico" },
  { name: "Beamer G16R", slug: "beamer-g16r", category: "civil", type: "Deportivo", priceCash: 175000, gold: 3600, topSpeed: 186, accel: "4.1s", rarity: "Épico" },
  { name: "Lambro Galante", slug: "lambro-galante", category: "civil", type: "Superdeportivo", priceCash: 180000, gold: 3700, topSpeed: 202, accel: "3.3s", rarity: "Épico" },
  { name: "Auvio RIO", slug: "auvio-rio", category: "civil", type: "Superdeportivo", priceCash: 250000, gold: 5000, topSpeed: 201, accel: "3.4s", rarity: "Épico" },
  { name: "Nissari Apex GT", slug: "nissari-apex-gt", category: "civil", type: "Superdeportivo", priceCash: 300000, gold: 6000, topSpeed: 196, accel: "2.8s", rarity: "Épico" },
  { name: "Mercel GT AMX", slug: "mercel-gt-amx", category: "civil", type: "Superdeportivo", priceCash: 300000, gold: 6000, topSpeed: 208, accel: "3.5s", rarity: "Épico" },
  { name: "Ducetti Streetfighter V4", slug: "ducetti-streetfighter-v4", category: "civil", type: "Moto", priceCash: 320000, gold: 6500, topSpeed: 186, accel: "2.6s", rarity: "Épico" },
  { name: "Koenix Gemina", slug: "koenix-gemina", category: "civil", type: "Hypercar", priceCash: 3000000, gold: 60000, topSpeed: 225, accel: "2.6s", rarity: "Legendario" },
  { name: "Fugatti Divino", slug: "fugatti-divino", category: "civil", type: "Hypercar", priceCash: 5000000, gold: 100000, topSpeed: 236, accel: "2.4s", rarity: "Legendario" },
  { name: "Mercel Aether Concept", slug: "mercel-aether-concept", category: "civil", type: "Hypercar", priceCash: 25000000, gold: 500000, topSpeed: 242, accel: "2.3s", rarity: "Legendario" },
  { name: "Hakura Vector R", slug: "hakura-vector-r", category: "civil", type: "Deportivo", priceCash: 0, priceLabel: "Recompensa diaria", gold: 3200, topSpeed: 167, accel: "5.0s", rarity: "Épico" },

  // ============ ROBUX (se compran con Robux) ============
  { name: "Transline Metro 40", slug: "transline-metro-40", category: "robux", type: "Minivan", robux: 499, gold: 950, topSpeed: 63, accel: "4.1s", rarity: "Raro" },
  { name: "Veylan Apex", slug: "veylan-apex", category: "robux", type: "Hypercar", robux: 599, gold: 1100, topSpeed: 212, accel: "2.3s", rarity: "Legendario" },
  { name: "Valenza Strada 70", slug: "valenza-strada-70", category: "robux", type: "Hypercar", robux: 699, gold: 1300, topSpeed: 205, accel: "2.8s", rarity: "Legendario" },
];

const RARITY_COLORS = {
  "Común": "#9aa5b1",
  "Raro": "#2f86eb",
  "Épico": "#a855f7",
  "Legendario": "#f59e0b",
};
